#Ghost Roles
- type: entity
  parent: BaseMindRole
  id: MindRoleGhostRoleEmotionalSupportPet
  name: Emotional Support Pet Role
  suffix: Frontier
  components:
  - type: MindRole
    roleType: EmotionalSupportPet
  - type: GhostRoleMarkerRole
